CRAIGSLIST_URLS = [
    "https://fortcollins.craigslist.org/search/elk-mountain-wy/cpg?bundleDuplicates=1&lat=41.5513&lon=-106.3441&postedToday=1&search_distance=960#search=2~thumb~0",
    "https://quincy.craigslist.org/search/williamstown-mo/cpg?bundleDuplicates=1&lat=40.2517&lon=-91.8421&postedToday=1&search_distance=1000",
    "https://quincy.craigslist.org/search/williamstown-mo/jjj?bundleDuplicates=1&excats=12-1-2-1-7-1-1-1-1-1-19-1-1-3-2-3-2-2-14-25-25-1-1-1-1-1-1&isTrusted=true&lat=40.2517&lon=-91.8421&postedToday=1&search_distance=1000#search=2~thumb~1",
    "https://fortcollins.craigslist.org/search/elk-mountain-wy/jjj?bundleDuplicates=1&excats=12-1-2-1-7-1-1-1-1-1-19-1-1-3-2-3-2-2-14-25-25-1-1-1-1-1-1&isTrusted=true&lat=41.5513&lon=-106.3441&postedToday=1&search_distance=960#search=2~thumb~0"
]
KEYWORDS = [
    "website development",
    "wordpress",
    "mobile app",
    "php",
    "laravel",
    "mern",
    "mean",
    "next.js",
    "react",
    "node.js",
    "full stack",
    "devops",
    "blockchain",
    "ethereum",
    "solidity",
    "nft",
    "3d artist",
    "digital marketing",
    "seo",
    "social media",
    "shopify",
    "wix",
    "e-commerce",
    "python",
    "django",
    "javascript",
    "typescript",
    "vue.js",
    "angular",
    "aws",
    "cloud",
    "database",
    "sql",
    "nosql",
    "mongodb",
    "postgresql",
    "ui/ux",
    "web design",
    "graphic design",
    "data science",
    "machine learning",
    "ai",
    "automation",
    "qa testing",
    "software testing",
    "system admin",
    "network",
    "cyber security",
    "flutter",
    "swift",
    "ios development",
    "android development",
    "game development"
]
REMOTE_KEYWORDS = [
    "remote ok",
    "remote only",
    "work from home",
    "telecommute",
    "fully remote",
    "anywhere",
    "virtual",
    "can be remote"
]
NON_REMOTE_KEYWORDS = [
    "local only",
    "local",
    "no remote",
    "on-site",
    "in-person",
    "usa only",
    "native only",
    "MUST BE LOCAL",
    "locally"
]
